# Generated by Django 3.1 on 2020-08-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
